In [3]:
import torch
from torch import tensor
torch.set_printoptions(linewidth=10000000, threshold=300000000)

In [4]:
input = torch.arange(64).reshape(8, 8)
input

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]])

In [5]:
def sample(max_val, sample_size):
    return torch.randperm(max_val)[:sample_size]

rows = (
    torch.stack([sample(4, 2) for _ in range(2)])
    * 4
)
cols = (
    torch.stack([sample(4, 2) for _ in range(2)])
    * 4
)
rows, cols

(tensor([[ 0,  4],
         [ 4, 12]]),
 tensor([[ 4,  8],
         [12,  0]]))

In [6]:
B = 2
num_patches = 2
patch_size = 4
rows = rows.repeat_interleave(patch_size**2, dim=1) + torch.arange(patch_size).repeat(num_patches * patch_size)
cols = cols.repeat_interleave(patch_size**2, dim=1) + torch.arange(patch_size).repeat_interleave(patch_size).repeat(num_patches)
rows, cols

(tensor([[ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3,  4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7],
         [ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7, 12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15]]),
 tensor([[ 4,  4,  4,  4,  5,  5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,  8,  8,  8,  8,  9,  9,  9,  9, 10, 10, 10, 10, 11, 11, 11, 11],
         [12, 12, 12, 12, 13, 13, 13, 13, 14, 14, 14, 14, 15, 15, 15, 15,  0,  0,  0,  0,  1,  1,  1,  1,  2,  2,  2,  2,  3,  3,  3,  3]]))

In [8]:
row_idxs = torch.arange(start=0, end=16, step=4).repeat(16 // 4)
col_idxs = torch.arange(start=0, end=16, step=4).repeat_interleave(16 // 4)
rows, cols

(tensor([[ 0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3,  0,  1,  2,  3,  4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7],
         [ 4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7,  4,  5,  6,  7, 12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15]]),
 tensor([[ 4,  4,  4,  4,  5,  5,  5,  5,  6,  6,  6,  6,  7,  7,  7,  7,  8,  8,  8,  8,  9,  9,  9,  9, 10, 10, 10, 10, 11, 11, 11, 11],
         [12, 12, 12, 12, 13, 13, 13, 13, 14, 14, 14, 14, 15, 15, 15, 15,  0,  0,  0,  0,  1,  1,  1,  1,  2,  2,  2,  2,  3,  3,  3,  3]]))

In [10]:
mask = torch.ones(1, 16, 16, dtype=bool) 
mask[:, rows[row_idxs], cols[col_idxs]] = False
mask


IndexError: index 4 is out of bounds for dimension 0 with size 2